### ISSUE TITLE
Unable to set Thermostat tempset

### ISSUE THREAD

**Issue by domenicoblanco** [kservices/gBridge#20]
Hi, first of all I really appreciate your work and I'd like to say thanks.
I'm having an issue when I try to set the Temperature and Humidity values with Temperature Setting's trait.
I tried to cast to int and float but it didn't work... The funny part is that if I change the device to Lamp and the trait to Brightness, it works but, if I try with Thermostat and Brightness as trait, it still doesn't work.

Thanks!

**Comment by peterkappelt** [comment]
Hi,

are you using the hosted gBridge service?

How do you observe, that your sent temperature/ humidity isn't applied?
What commands are you asking Google?

Am So., 9. Dez. 2018, 02:22 hat Domenico Blanco <notifications@github.com>
geschrieben:

**Comment by domenicoblanco** [comment]
Hi, I'm using the hosted gBridge service. I o serve that Temperature and Humidity aren't applied insider the Google Home App: when I click on thermostat, It says only the device nane and the room. I tried to ask the following command: "Hey Google, how many degrees in <thermostat name>?". I also noticed that I never receive Actions Topics also when I connect and publish infos during on_connect

**Comment by peterkappelt** [comment]
Mhh, strange. It works without any issues for me, even with a newly created thermostat device.

Did you make any changes to this device? Are you using the most recent version of the Google Home app?

Look at the attached screenshots, it is like that for me.
![home](https://user-images.githubusercontent.com/13392434/49696810-c7848700-fbaf-11e8-822b-eebf0f9aac21.png)
![mqtt](https://user-images.githubusercontent.com/13392434/49696812-d8cd9380-fbaf-11e8-8de4-181a2a750b66.png)

The problem with the Google search (instead of the real answer) is about the semantics of your question. Google is currently quite picky with the commands that are supported for thermostats. They highly depend on your selected language. If you've got english enabled (e.g. as the seconds language), the question "Hey Google, what's the temperature in here?" works for me.

**Comment by domenicoblanco** [comment]
I was interested only in Temperature and Humidity about the thermostat (I've a DHT11 sensor), so I updated only 2 traits. When I noticed it wasn't working I also subscribed to both Action Topics and updated the status of thermostat to on. I'm quite sure that I tried all of the possibilities :/
I tried to use Brightness to test if it was my fault but I send the exact message to both this devices and in one works and in the other one doesn't. 
![photo_2018-12-09_12-48-51](https://user-images.githubusercontent.com/9018104/49696927-71b0de80-fbb1-11e8-8b3a-73f0efcf1b8f.jpg)
![photo_2018-12-09_12-48-45](https://user-images.githubusercontent.com/9018104/49696930-783f5600-fbb1-11e8-97fd-244439a1d5f3.jpg)

I'm sure it's the latest version of Google Home App. I'll try to add English as second language and test, but as it doesn't show them inside the app, I don't think it will with Assistant

**Comment by domenicoblanco** [comment]
Update: I tried with English as second language and it says "Unable to reach the product"

**Comment by domenicoblanco** [comment]
I made some tests and apparently It brokes when I update humidity. Any suggestion?

**Comment by peterkappelt** [comment]
Have you enabled the feature "Device is able to report humidity" when editing the thermostat device?

No humidity should be sent to Google if this is disabled. However, due to a bug, sending a humidity without this feature being enabled completely broke this device. It is fixed now.

**Comment by domenicoblanco** [comment]
Yeah, now it works! But is it normal that humidity percentage isn't visible inside Google Home App?
![photo_2018-12-09_23-51-23](https://user-images.githubusercontent.com/9018104/49704015-6390ab80-fc0d-11e8-8d19-d023c6920ba6.jpg)

**Comment by peterkappelt** [comment]
Yes, sadly it is normal.
Thank Google for it 😢

**Comment by domenicoblanco** [comment]
Thanks Google 😭 
But really thanks to you! As the error is fixed, I think that we could close the issue!
