### ISSUE TITLE
responded number of devices wrong when switching all lights in a room

### ISSUE THREAD

**Issue by JurikRistjouw** [kservices/gBridge#21]
I have 4 devices in the Attic. 2 Of which there are lights with the corresponding icon. When i tell gbridge to turn on all lights, google responds with, ok turning on 6!! devices, but turns on 2 lights only. offcourse, this is the favoured result, but the correct response should be, ok turning on 2 lights. 

when switching on all devices, the answer is 8!! and result are 4 devices turned on.

the total amount of devices in gbridge is 8....

edit: after a new push from domoticz, i have a response with more devices currently 8, was 6 before and 4 before that...  (only 2 lights still in the attic)

**Comment by JurikRistjouw** [comment]
seems that with every push from domoticz (in hardware tab, push on update on gbridge) the device count adds up...

**Comment by peterkappelt** [comment]
Have you checked your gBridge account, whether the amount/ kinds of devices in your portal matches your expected ones?

**Comment by JurikRistjouw** [comment]
yes I did. in the portal the correct number is displayed (no doubles). It seems the problem corrected itself somehow. I get a correct response when asking for all lights in the room, namely 2. I think it can be closed.

could it be that in the portal, you use a distinct query for the devices?

**Comment by peterkappelt** [comment]
No, all devices are displayed in the management portal, even duplicates.

I haven't look into the Domoticz implementation in detail. I could imagine, that upon a push from Domoticz it deletes all devices and re-creates them. In this case, it is a synchronization delay with Google Home. It takes some time for all devices to disappear, after they've been deleted. Re-linking of your Google 

I suppose this problem is solved now, thus the issue can be closed?
